In [4]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

In [7]:
# build two models

widenet = nn.Sequential(
    nn.Linear(2,4),    # hidden layer
    nn.Linear(4,3),    # output layer
    )

deepnet = nn.Sequential(
    nn.Linear(2,2),    # hidden layer
    nn.Linear(2,2),    # hidden layer
    nn.Linear(2,3),    # output layer
)

#print. them out to have a look
print(widenet)
print(' ')
print(deepnet)

'''
These networks are instances of a class in Pytorch.
widenet. will open all list of attributes and methods associated with the instance.
We will only use soe properties there.
'''

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [9]:
# Peeking inside the network
# check out the parameters

for p in deepnet.named_parameters():
    print(p)
    print(' ')

('0.weight', Parameter containing:
tensor([[-0.2873, -0.6458],
        [ 0.4653, -0.6022]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([-0.2887, -0.0568], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[ 0.0768,  0.4199],
        [ 0.1043, -0.1194]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([-0.3526, -0.4825], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[-0.6315,  0.0978],
        [ 0.7006, -0.2562],
        [ 0.3798,  0.3768]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([-0.0209,  0.5128,  0.0696], requires_grad=True))
 


In [13]:
# count the number of nodeaa ( = the number of biases )

# named_parameters() is an iterable that returns the tuple (name,numbers)
numNodesInWide = 0
for p in widenet.named_parameters():
    if 'bias' in p[0]:
        numNodesInWide += len(p[1])

numNodesInDeep = 0
for paramName,paramVect in deepnet.named_parameters():
    if 'bias' in paramName:
        numNodesInDeep += len(paramVect)
        
print('There are %s nodes in the wide network.' %numNodesInWide)
print('There are %s nodes in the deep network.' %numNodesInDeep)

There are 7 nodes in the wide network.
There are 7 nodes in the deep network.


In [14]:
# just the parameters
for p in widenet.parameters():
    print(p)
    print(' ')

Parameter containing:
tensor([[-0.3167,  0.4767],
        [ 0.4539,  0.2336],
        [-0.1467, -0.3039],
        [ 0.4970,  0.0928]], requires_grad=True)
 
Parameter containing:
tensor([ 0.2659, -0.6594, -0.2807, -0.6570], requires_grad=True)
 
Parameter containing:
tensor([[ 0.0742,  0.2184,  0.3265,  0.0120],
        [ 0.3631, -0.3049,  0.1597,  0.1585],
        [-0.4567,  0.1874,  0.3646,  0.0939]], requires_grad=True)
 
Parameter containing:
tensor([ 0.3179,  0.4567, -0.2965], requires_grad=True)
 


In [15]:
# now count the total no of trainable parameters
nparams=0
for p in widenet.parameters():
    if p.requires_grad:
        print('This piece has %s parameters' %p.numel())
        nparams += p.numel()

print('\n\nTotal of %s parameters'%nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameters


In [16]:
# We can also use list comprehension

nparams = np.sum([p.numel() for p in widenet.parameters() if p.requires_grad])
print('Widenet has %s parameters' %nparams)

nparams = np.sum([p.numel() for p in deepnet.parameters() if p.requires_grad])
print('deepnet has %s parameters'%nparams)

Widenet has 27 parameters
deepnet has 21 parameters


In [20]:
pip install torchsummary

Note: you may need to restart the kernel to use updated packages.


In [24]:
# Nice way to print model info.
from torchsummary import summary
summary(widenet, input_size=(1, 2))


----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
            Linear-2                 [-1, 1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
